services:
    en-memoria:
        build: .
        ports:
            - "3000:3000"
        environment:
            - LOCATION_LATITUDE=33.8959
            - LOCATION_LONGITUDE=-118.2201
            - NEXT_PUBLIC_LOCATION_CITY=Compton
            - PHOTO_DIRECTORY=/app/photos
        volumes:
            - G:/syncthing/photos:/app/photos
